import {StyleSheet} from 'react-native';
import theme from './theme';
export default CommonStyles = StyleSheet.create({
  primarycolor: {color: '#57BCB6'},
  accentcolor: {color: '#323638'},
  backgroundImageStyle: {flex: 1, resizeMode: 'cover', alignSelf: 'stretch'},
  backgroundImageStylePlan: {
    flex: 1,
    position: 'absolute',
    resizeMode: 'contain',
    width: '100%',
    height: '70%',
  },
  headerstyle: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    padding: 2,
  },

  headerstylemodal: {
    flex: 0.11,
    flexDirection: 'row',
    justifyContent: 'center',
    padding: 2,
  },

  headerstyleprogram: {
    flex: 0.24,
    flexDirection: 'row',
    justifyContent: 'center',
    padding: 2,
  },
  header: {
    padding: 5,
    textAlign: 'center',
    fontSize: 26,
    color: theme.textcolor,
    fontWeight: 'bold',
    fontFamily: theme.fontBold,
  },
  infoheader: {
    padding: 5,
    textAlign: 'center',
    fontSize: 26,
    color: theme.primary,
    fontWeight: 'bold',
  },
  subheaderstyle: {
    paddingHorizontal: 5,
    textAlign: 'left',
    fontSize: 20,
    color: theme.textcolor,
    fontWeight: 'bold',
    fontFamily: theme.fontBold,
  },
  subheaderleft: {
    padding: 5,
    paddingHorizontal: 5,
    textAlign: 'left',
    fontSize: 18,
    color: theme.textcolor,
    fontFamily: theme.font,
  },
  palceholderstyle: {
    paddingLeft: 20,
    justifyContent: 'flex-start',
    fontSize: 20,
    color: theme.textinputplaceholder,
  },
  subheadercenter: {
    padding: 5,
    textAlign: 'center',
    justifyContent: 'center',
    fontSize: 18,
    color: theme.primary,
  },
  paracenter: {
    padding: 5,
    textAlign: 'center',
    fontSize: 18,
    color: 'black',
    fontFamily: theme.font,
  },
  paraLeft: {
    padding: 5,
    justifyContent: 'flex-start',
    fontSize: 18,
    color: 'black',
    fontFamily: theme.font,
  },
  vatTextStyle: {
    marginTop: 5,
    padding: 5,
    justifyContent: 'center',
    fontSize: 14,
    color: 'black',
    fontWeight: 'bold',
    fontFamily: theme.font,
  },
  textstyle: {
    flex: 1,
    paddingTop: 8,
    justifyContent: 'flex-start',
    color: theme.textcolor,
    fontSize: 18,
    fontFamily: theme.font,
  },
  policyBenefitTextstyle: {
    flex: 1,
    paddingHorizontal: 10,
    justifyContent: 'flex-start',
    color: theme.textcolor,
    fontSize: 18,
    fontFamily: theme.font,
  },
  // buttontextstyle: {
  //   color: theme.textcolor,
  //   textAlign: 'center',
  //   fontSize: 18,
  //   fontWeight: 'bold',
  // },
  textinputstyle: {
    flex: 1,
    paddingHorizontal: 5,
    flexDirection: 'column',
    backgroundColor: '#66000000',
    justifyContent: 'center',
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: theme.bordercolor,
    fontFamily: theme.font,
  },
  dropdownstyle: {
    flex: 1,
    paddingHorizontal: 5,
    flexDirection: 'column',
    backgroundColor: '#66000000',
    justifyContent: 'center',
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: theme.bordercolor,
    shadowOffset: {width: 0, height: 5},
    shadowRadius: 10,
    shadowOpacity: 0.35,
  },
  dropdownFormStyle: {
    flex: 0.48,
    paddingHorizontal: 10,
    flexDirection: 'column',
    backgroundColor: '#66000000',
    justifyContent: 'space-between',
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: theme.bordercolor,
  },
  dropdownPersonalStyle: {
    flex: 0.5,
    paddingHorizontal: 5,
    flexDirection: 'row',
    backgroundColor: '#66000000',
    justifyContent: 'space-between',
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: theme.bordercolor,
  },
});
